/* eslint-disable max-len */
/* eslint-disable import/prefer-default-export */

export const ARTICLE_CONTENT = {
    ARTICLE_CONTENT_READ1:
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim. Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Cursus vitae congue mauris rhoncus aenean vel elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim. Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Cursus vitae.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim. Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Cursus vitae congue mauris
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim. Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Cursus vitae congue mauris rhoncus aenean vel elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim. Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Cursus vitae.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim. Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Cursus vitae congue mauris
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim. Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Cursus vitae congue mauris rhoncus aenean vel elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim.`,
    ARTICLE_CONTENT_READ2:
    `Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim. Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Cursus vitae congue mauris
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim. Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Cursus vitae congue mauris rhoncus aenean vel elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim. Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Cursus vitae.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim. Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Cursus vitae congue mauris
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim. Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Cursus vitae congue mauris rhoncus aenean vel elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim. Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Cursus vitae.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc non blandit massa enim. Donec enim diam vulputate ut pharetra sit. Id faucibus nisl tincidunt eget nullam. Vitae congue eu consequat ac felis donec et odio pellentesque. Cursus vitae congue mauris`,
    COMMENT_TEXT1:
    'This application looks far too advance for this Naija o.',
    COMMENT_TEXT2:
    'This application looks far too advance for this Naija o.',
    COMMENT_TEXT3:
    'This application looks kinda too much for Nigeria.',
};
